apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-flask-k8s
  name: sample-flask-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-flask-k8s
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-flask-k8s
    spec:
      containers:
      - image: marcosportorc/webapp:030f582a3b8d56d71eb01b585961506214f7dd37
        name: sample-flask-k8s
        ports:
        - containerPort: 5000
