apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-flask-k8s
  name: sample-flask-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-flask-k8s
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-flask-k8s
    spec:
      affinity:
        podAffinity:
          maxUnavailable: 2
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - my-app
            topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - my-app
            topologyKey: kubernetes.io/hostname
      containers:
      - image: sample-flask-k8s
        name: sample-flask-k8s
        ports:
        - containerPort: 5000
