apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-flask-k8s
  name: sample-flask-k8s
spec:
  ports:
  - name: 5000-5000
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: sample-flask-k8s
  type: LoadBalancer

